JBR-6071 Alpine Linux compilation: error: implicit declaration of function 'pthread_getname_np'
(cherry picked from commit 72722dac363c5c662e81a401d33ad48c563da5b2)